package core

import "core:os"
import "core:testing"

@(test)
test_read_only_denies_write_and_bash :: proc(t: ^testing.T) {
	d := check_tool(.Read_Only, "search_replace", "", nil, nil)
	testing.expect(t, d == .Deny, "edit denied")
	d = check_tool(.Read_Only, "run_terminal_cmd", "rm foo", nil, nil)
	testing.expect(t, d == .Deny, "write bash denied")
	d = check_tool(.Read_Only, "read_file", "", nil, nil)
	testing.expect(t, d == .Allow, "read allowed")
	d = check_tool(.Read_Only, "web_search", "", nil, nil)
	testing.expect(t, d == .Allow, "web_search allowed")
}

@(test)
test_always_approve_allows_edit :: proc(t: ^testing.T) {
	d := check_tool(.Always_Approve, "search_replace", "", nil, nil)
	testing.expect(t, d == .Allow)
	d = check_tool(.Ask, "run_terminal_cmd", "rm foo", nil, nil)
	testing.expect(t, d == .Ask)
}

@(test)
test_deny_rule_bash_rm :: proc(t: ^testing.T) {
	deny := []string{"Bash(rm -rf *)"}
	d := check_tool(.Always_Approve, "run_terminal_cmd", "rm -rf /tmp/x", nil, deny)
	testing.expect(t, d == .Deny, "rm denied by rule")
	d = check_tool(.Always_Approve, "run_terminal_cmd", "ls", nil, deny)
	testing.expect(t, d == .Allow, "ls allowed")
}

@(test)
test_match_simple_glob :: proc(t: ^testing.T) {
	testing.expect(t, match_simple_glob("git *", "git status"))
	testing.expect(t, match_simple_glob("rm -rf *", "rm -rf /tmp"))
	testing.expect(t, !match_simple_glob("git *", "cargo build"))
	// multi-star (Grok Bash(git * main) style — literal " main" suffix)
	testing.expect(t, match_simple_glob("git * main", "git checkout main"))
	testing.expect(t, match_simple_glob("git * main", "git merge main"))
	testing.expect(t, !match_simple_glob("git * main", "git merge origin/main")) // no " main"
	testing.expect(t, !match_simple_glob("git * main", "git checkout feature"))
	testing.expect(t, match_simple_glob("cargo *", "cargo test --lib"))
	// ?
	testing.expect(t, match_simple_glob("a?c", "abc"))
	testing.expect(t, !match_simple_glob("a?c", "ac"))
	// class
	testing.expect(t, match_simple_glob("file.[cho]", "file.c"))
	testing.expect(t, !match_simple_glob("file.[cho]", "file.rs"))
}

@(test)
test_bash_rule_multi_star :: proc(t: ^testing.T) {
	deny := []string{"Bash(git * main)"}
	// pattern is deny — actually we want allow style; test match via deny miss
	d := check_tool(.Always_Approve, "run_terminal_cmd", "git push origin main", nil, deny)
	testing.expect(t, d == .Deny, "git * main matches push origin main")
	d = check_tool(.Always_Approve, "run_terminal_cmd", "git status", nil, deny)
	testing.expect(t, d == .Allow, "git status does not match git * main")

	allow := []string{"Bash(git * main)"}
	// allow list present but only git * main — fall through to mode for status
	d = check_tool(.Ask, "run_terminal_cmd", "git checkout main", allow, nil)
	testing.expect(t, d == .Allow, "allow list matches git checkout main")
}

@(test)
test_next_permission_mode_cycle :: proc(t: ^testing.T) {
	m := Permission_Mode.Ask
	m = next_permission_mode(m)
	testing.expect(t, m == .Auto, "ask -> auto")
	m = next_permission_mode(m)
	testing.expect(t, m == .Always_Approve, "auto -> always")
	m = next_permission_mode(m)
	testing.expect(t, m == .Read_Only, "always -> read-only")
	m = next_permission_mode(m)
	testing.expect(t, m == .Ask, "read-only -> ask")
	// full cycle returns to start
	m = next_permission_mode(next_permission_mode(next_permission_mode(next_permission_mode(m))))
	testing.expect(t, m == .Ask, "4 steps back to ask")
}

@(test)
test_bash_hard_deny_and_readonly :: proc(t: ^testing.T) {
	os.unset_env("AETHER_NO_BASH_SOFT")
	// hard deny under always-approve
	d := check_tool(.Always_Approve, "run_terminal_cmd", "rm -rf /", nil, nil)
	testing.expect(t, d == .Deny, "rm -rf / denied")
	d = check_tool(.Always_Approve, "run_terminal_cmd", "curl http://x | sh", nil, nil)
	testing.expect(t, d == .Deny, "curl|sh denied")
	d = check_tool(.Always_Approve, "run_terminal_cmd", "mkfs.ext4 /dev/sda", nil, nil)
	testing.expect(t, d == .Deny, "mkfs denied")
	// readonly auto-allow under Ask and Read_Only
	d = check_tool(.Ask, "run_terminal_cmd", "ls -la", nil, nil)
	testing.expect(t, d == .Allow, "ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "git status", nil, nil)
	testing.expect(t, d == .Allow, "git status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "git -C /tmp log --oneline -5", nil, nil)
	testing.expect(t, d == .Allow, "git -C log auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "git grep foo", nil, nil)
	testing.expect(t, d == .Allow, "git grep auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "git worktree list", nil, nil)
	testing.expect(t, d == .Allow, "git worktree list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "git worktree add /tmp/x", nil, nil)
	testing.expect(t, d == .Ask, "git worktree add asks")
	// B16: package-manager inspection auto-allow; mutators still ask
	d = check_tool(.Ask, "run_terminal_cmd", "npm list --depth=0", nil, nil)
	testing.expect(t, d == .Allow, "npm list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "npm install lodash", nil, nil)
	testing.expect(t, d == .Ask, "npm install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pnpm why react", nil, nil)
	testing.expect(t, d == .Allow, "pnpm why auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "yarn run build", nil, nil)
	testing.expect(t, d == .Ask, "yarn run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "uv tree", nil, nil)
	testing.expect(t, d == .Allow, "uv tree auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "uv sync", nil, nil)
	testing.expect(t, d == .Ask, "uv sync asks")
	d = check_tool(.Ask, "run_terminal_cmd", "rustup show", nil, nil)
	testing.expect(t, d == .Allow, "rustup show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pip list", nil, nil)
	testing.expect(t, d == .Allow, "pip list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "python --version", nil, nil)
	testing.expect(t, d == .Allow, "python --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "python -c 'print(1)'", nil, nil)
	testing.expect(t, d == .Ask, "python -c asks")
	d = check_tool(.Ask, "run_terminal_cmd", "go version", nil, nil)
	testing.expect(t, d == .Allow, "go version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "go mod tidy", nil, nil)
	testing.expect(t, d == .Ask, "go mod tidy asks")
	d = check_tool(.Ask, "run_terminal_cmd", "cargo metadata --format-version 1", nil, nil)
	testing.expect(t, d == .Allow, "cargo metadata auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "cargo build", nil, nil)
	testing.expect(t, d == .Ask, "cargo build asks")
	// B25: make / odin / pytest inspect
	d = check_tool(.Ask, "run_terminal_cmd", "make help", nil, nil)
	testing.expect(t, d == .Allow, "make help auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "make -n all", nil, nil)
	testing.expect(t, d == .Allow, "make -n auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "make build", nil, nil)
	testing.expect(t, d == .Ask, "make build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "odin version", nil, nil)
	testing.expect(t, d == .Allow, "odin version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "odin build .", nil, nil)
	testing.expect(t, d == .Ask, "odin build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pytest --collect-only", nil, nil)
	testing.expect(t, d == .Allow, "pytest --collect-only auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pytest tests/", nil, nil)
	testing.expect(t, d == .Ask, "pytest run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "python -m pytest --co", nil, nil)
	testing.expect(t, d == .Allow, "python -m pytest --co auto-allow")
	// B28: cmake / ninja / meson inspect
	d = check_tool(.Ask, "run_terminal_cmd", "cmake --version", nil, nil)
	testing.expect(t, d == .Allow, "cmake --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "cmake -B build", nil, nil)
	testing.expect(t, d == .Ask, "cmake configure asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ninja -t targets", nil, nil)
	testing.expect(t, d == .Allow, "ninja -t targets auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ninja all", nil, nil)
	testing.expect(t, d == .Ask, "ninja build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "meson introspect --targets", nil, nil)
	testing.expect(t, d == .Allow, "meson introspect auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "meson compile", nil, nil)
	testing.expect(t, d == .Ask, "meson compile asks")
	// B31: just inspect auto-allow; recipe run asks
	d = check_tool(.Ask, "run_terminal_cmd", "just --list", nil, nil)
	testing.expect(t, d == .Allow, "just --list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "just -l", nil, nil)
	testing.expect(t, d == .Allow, "just -l auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "just --show build", nil, nil)
	testing.expect(t, d == .Allow, "just --show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "just --version", nil, nil)
	testing.expect(t, d == .Allow, "just --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "just", nil, nil)
	testing.expect(t, d == .Ask, "bare just asks")
	d = check_tool(.Ask, "run_terminal_cmd", "just build", nil, nil)
	testing.expect(t, d == .Ask, "just recipe asks")
	d = check_tool(.Ask, "run_terminal_cmd", "just --fmt", nil, nil)
	testing.expect(t, d == .Ask, "just --fmt asks")
	// B33: gh inspect auto-allow; mutators ask
	d = check_tool(.Ask, "run_terminal_cmd", "gh pr list", nil, nil)
	testing.expect(t, d == .Allow, "gh pr list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh pr view 1", nil, nil)
	testing.expect(t, d == .Allow, "gh pr view auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh pr status", nil, nil)
	testing.expect(t, d == .Allow, "gh pr status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh pr diff 1", nil, nil)
	testing.expect(t, d == .Allow, "gh pr diff auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh issue list", nil, nil)
	testing.expect(t, d == .Allow, "gh issue list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh repo view", nil, nil)
	testing.expect(t, d == .Allow, "gh repo view auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh status", nil, nil)
	testing.expect(t, d == .Allow, "gh status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh auth status", nil, nil)
	testing.expect(t, d == .Allow, "gh auth status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh api repos/o/r", nil, nil)
	testing.expect(t, d == .Allow, "gh api GET auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gh pr create", nil, nil)
	testing.expect(t, d == .Ask, "gh pr create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gh pr merge 1", nil, nil)
	testing.expect(t, d == .Ask, "gh pr merge asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gh issue create --title x", nil, nil)
	testing.expect(t, d == .Ask, "gh issue create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gh api graphql -f query=x", nil, nil)
	testing.expect(t, d == .Ask, "gh api graphql asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gh api -X POST repos/o/r", nil, nil)
	testing.expect(t, d == .Ask, "gh api POST asks")
	// B35: docker / docker compose inspect
	d = check_tool(.Ask, "run_terminal_cmd", "docker ps", nil, nil)
	testing.expect(t, d == .Allow, "docker ps auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "docker compose ps", nil, nil)
	testing.expect(t, d == .Allow, "docker compose ps auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "docker compose config", nil, nil)
	testing.expect(t, d == .Allow, "docker compose config auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "docker compose -f compose.yml logs", nil, nil)
	testing.expect(t, d == .Allow, "docker compose -f logs auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "docker-compose ps", nil, nil)
	testing.expect(t, d == .Allow, "docker-compose ps auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "docker compose up -d", nil, nil)
	testing.expect(t, d == .Ask, "docker compose up asks")
	d = check_tool(.Ask, "run_terminal_cmd", "docker compose build", nil, nil)
	testing.expect(t, d == .Ask, "docker compose build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "docker run alpine", nil, nil)
	testing.expect(t, d == .Ask, "docker run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "docker exec c ls", nil, nil)
	testing.expect(t, d == .Ask, "docker exec asks")
	// B36: terraform / helm / expanded kubectl
	d = check_tool(.Ask, "run_terminal_cmd", "terraform plan", nil, nil)
	testing.expect(t, d == .Allow, "terraform plan auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform validate", nil, nil)
	testing.expect(t, d == .Allow, "terraform validate auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform fmt -check", nil, nil)
	testing.expect(t, d == .Allow, "terraform fmt -check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform state list", nil, nil)
	testing.expect(t, d == .Allow, "terraform state list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tofu version", nil, nil)
	testing.expect(t, d == .Allow, "tofu version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform apply", nil, nil)
	testing.expect(t, d == .Ask, "terraform apply asks")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform plan -out=tf.plan", nil, nil)
	testing.expect(t, d == .Ask, "terraform plan -out asks")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform fmt", nil, nil)
	testing.expect(t, d == .Ask, "terraform fmt writes asks")
	d = check_tool(.Ask, "run_terminal_cmd", "helm list", nil, nil)
	testing.expect(t, d == .Allow, "helm list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helm status myrel", nil, nil)
	testing.expect(t, d == .Allow, "helm status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helm template ch ./chart", nil, nil)
	testing.expect(t, d == .Allow, "helm template auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helm install ch ./chart", nil, nil)
	testing.expect(t, d == .Ask, "helm install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "kubectl get pods", nil, nil)
	testing.expect(t, d == .Allow, "kubectl get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubectl config view", nil, nil)
	testing.expect(t, d == .Allow, "kubectl config view auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubectl apply -f x.yaml", nil, nil)
	testing.expect(t, d == .Ask, "kubectl apply asks")
	// B38: bun / deno / poetry inspect
	d = check_tool(.Ask, "run_terminal_cmd", "bun --version", nil, nil)
	testing.expect(t, d == .Allow, "bun --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bun pm ls", nil, nil)
	testing.expect(t, d == .Allow, "bun pm ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bun install", nil, nil)
	testing.expect(t, d == .Ask, "bun install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "bun run dev", nil, nil)
	testing.expect(t, d == .Ask, "bun run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "deno --version", nil, nil)
	testing.expect(t, d == .Allow, "deno --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "deno info main.ts", nil, nil)
	testing.expect(t, d == .Allow, "deno info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "deno check main.ts", nil, nil)
	testing.expect(t, d == .Allow, "deno check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "deno fmt --check", nil, nil)
	testing.expect(t, d == .Allow, "deno fmt --check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "deno run main.ts", nil, nil)
	testing.expect(t, d == .Ask, "deno run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "poetry show", nil, nil)
	testing.expect(t, d == .Allow, "poetry show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "poetry env info", nil, nil)
	testing.expect(t, d == .Allow, "poetry env info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "poetry check", nil, nil)
	testing.expect(t, d == .Allow, "poetry check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "poetry install", nil, nil)
	testing.expect(t, d == .Ask, "poetry install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "poetry run pytest", nil, nil)
	testing.expect(t, d == .Ask, "poetry run asks")
	// B40: zig inspect
	d = check_tool(.Ask, "run_terminal_cmd", "zig version", nil, nil)
	testing.expect(t, d == .Allow, "zig version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "zig env", nil, nil)
	testing.expect(t, d == .Allow, "zig env auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "zig ast-check file.zig", nil, nil)
	testing.expect(t, d == .Allow, "zig ast-check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "zig fmt --check .", nil, nil)
	testing.expect(t, d == .Allow, "zig fmt --check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "zig build", nil, nil)
	testing.expect(t, d == .Ask, "zig build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "zig fmt .", nil, nil)
	testing.expect(t, d == .Ask, "zig fmt write asks")
	// B42: swift / dotnet inspect
	d = check_tool(.Ask, "run_terminal_cmd", "swift --version", nil, nil)
	testing.expect(t, d == .Allow, "swift --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "swift package describe", nil, nil)
	testing.expect(t, d == .Allow, "swift package describe auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "swift package show-dependencies", nil, nil)
	testing.expect(t, d == .Allow, "swift package show-dependencies auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "swift package resolve", nil, nil)
	testing.expect(t, d == .Ask, "swift package resolve asks")
	d = check_tool(.Ask, "run_terminal_cmd", "swift build", nil, nil)
	testing.expect(t, d == .Ask, "swift build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "dotnet --info", nil, nil)
	testing.expect(t, d == .Allow, "dotnet --info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dotnet --list-sdks", nil, nil)
	testing.expect(t, d == .Allow, "dotnet --list-sdks auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dotnet tool list", nil, nil)
	testing.expect(t, d == .Allow, "dotnet tool list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dotnet build", nil, nil)
	testing.expect(t, d == .Ask, "dotnet build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "dotnet run", nil, nil)
	testing.expect(t, d == .Ask, "dotnet run asks")
	// B43: sqlite3 / redis-cli inspect
	d = check_tool(.Ask, "run_terminal_cmd", "sqlite3 -version", nil, nil)
	testing.expect(t, d == .Allow, "sqlite3 -version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", `sqlite3 db.sqlite ".tables"`, nil, nil)
	testing.expect(t, d == .Allow, "sqlite3 .tables auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "sqlite3 db.sqlite 'SELECT 1'", nil, nil)
	testing.expect(t, d == .Allow, "sqlite3 SELECT auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "sqlite3 db.sqlite 'DELETE FROM t'", nil, nil)
	testing.expect(t, d == .Ask, "sqlite3 DELETE asks")
	d = check_tool(.Ask, "run_terminal_cmd", "sqlite3", nil, nil)
	testing.expect(t, d == .Ask, "bare sqlite3 asks")
	d = check_tool(.Ask, "run_terminal_cmd", "redis-cli ping", nil, nil)
	testing.expect(t, d == .Allow, "redis-cli ping auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "redis-cli info", nil, nil)
	testing.expect(t, d == .Allow, "redis-cli info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "redis-cli get key", nil, nil)
	testing.expect(t, d == .Allow, "redis-cli get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "redis-cli set k v", nil, nil)
	testing.expect(t, d == .Ask, "redis-cli set asks")
	d = check_tool(.Ask, "run_terminal_cmd", "redis-cli flushall", nil, nil)
	testing.expect(t, d == .Ask, "redis-cli flushall asks")
	// B44: psql / mysql inspect
	d = check_tool(.Ask, "run_terminal_cmd", "psql --version", nil, nil)
	testing.expect(t, d == .Allow, "psql --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", `psql -c "SELECT 1"`, nil, nil)
	testing.expect(t, d == .Allow, "psql SELECT auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", `psql -c "\dt"`, nil, nil)
	testing.expect(t, d == .Allow, "psql \\dt auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "psql -l", nil, nil)
	testing.expect(t, d == .Allow, "psql -l auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", `psql -c "DELETE FROM t"`, nil, nil)
	testing.expect(t, d == .Ask, "psql DELETE asks")
	d = check_tool(.Ask, "run_terminal_cmd", "psql", nil, nil)
	testing.expect(t, d == .Ask, "bare psql asks")
	d = check_tool(.Ask, "run_terminal_cmd", "mysql --version", nil, nil)
	testing.expect(t, d == .Allow, "mysql --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", `mysql -e "SELECT 1"`, nil, nil)
	testing.expect(t, d == .Allow, "mysql SELECT auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", `mysql -e "SHOW TABLES"`, nil, nil)
	testing.expect(t, d == .Allow, "mysql SHOW auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", `mysql -e "DELETE FROM t"`, nil, nil)
	testing.expect(t, d == .Ask, "mysql DELETE asks")
	d = check_tool(.Ask, "run_terminal_cmd", "mariadb -e 'SELECT 1'", nil, nil)
	testing.expect(t, d == .Allow, "mariadb SELECT auto-allow")
	// B46: curl / wget / ffprobe inspect
	d = check_tool(.Ask, "run_terminal_cmd", "curl --version", nil, nil)
	testing.expect(t, d == .Allow, "curl --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "curl -I https://example.com", nil, nil)
	testing.expect(t, d == .Allow, "curl -I auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "curl -sS https://example.com", nil, nil)
	testing.expect(t, d == .Allow, "curl GET auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "curl -X POST https://example.com", nil, nil)
	testing.expect(t, d == .Ask, "curl POST asks")
	d = check_tool(.Ask, "run_terminal_cmd", "curl -o out.html https://example.com", nil, nil)
	testing.expect(t, d == .Ask, "curl -o asks")
	d = check_tool(.Ask, "run_terminal_cmd", "curl -d a=1 https://example.com", nil, nil)
	testing.expect(t, d == .Ask, "curl -d asks")
	d = check_tool(.Ask, "run_terminal_cmd", "wget --spider https://example.com", nil, nil)
	testing.expect(t, d == .Allow, "wget --spider auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "wget -O - https://example.com", nil, nil)
	testing.expect(t, d == .Allow, "wget -O - auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "wget https://example.com", nil, nil)
	testing.expect(t, d == .Ask, "wget download asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ffprobe -v quiet -show_format file.mp4", nil, nil)
	testing.expect(t, d == .Allow, "ffprobe auto-allow")
	// B49: eza/fd viewers + ffmpeg -i probe
	d = check_tool(.Ask, "run_terminal_cmd", "eza -la", nil, nil)
	testing.expect(t, d == .Allow, "eza auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "fd '.odin$'", nil, nil)
	testing.expect(t, d == .Allow, "fd auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ffmpeg -i clip.mp4", nil, nil)
	testing.expect(t, d == .Allow, "ffmpeg -i auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ffmpeg -hide_banner -i clip.mp4", nil, nil)
	testing.expect(t, d == .Allow, "ffmpeg -hide_banner -i auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ffmpeg -i in.mp4 out.mp4", nil, nil)
	testing.expect(t, d == .Ask, "ffmpeg encode asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ffmpeg -i in.mp4 -c:v libx264 out.mp4", nil, nil)
	testing.expect(t, d == .Ask, "ffmpeg -c:v asks")
	// B51: httpie / xh GET
	d = check_tool(.Ask, "run_terminal_cmd", "http --version", nil, nil)
	testing.expect(t, d == .Allow, "http --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "http GET https://example.com", nil, nil)
	testing.expect(t, d == .Allow, "http GET auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "xh https://example.com", nil, nil)
	testing.expect(t, d == .Allow, "xh URL auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "http POST https://example.com hello=world", nil, nil)
	testing.expect(t, d == .Ask, "http POST asks")
	d = check_tool(.Ask, "run_terminal_cmd", "xh -d https://example.com", nil, nil)
	testing.expect(t, d == .Ask, "xh download asks")
	// B52: modern viewers
	d = check_tool(.Ask, "run_terminal_cmd", "dust .", nil, nil)
	testing.expect(t, d == .Allow, "dust auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "duf", nil, nil)
	testing.expect(t, d == .Allow, "duf auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "procs", nil, nil)
	testing.expect(t, d == .Allow, "procs auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tokei .", nil, nil)
	testing.expect(t, d == .Allow, "tokei auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "delta --version", nil, nil)
	testing.expect(t, d == .Allow, "delta auto-allow")
	// B54: nix inspect
	d = check_tool(.Ask, "run_terminal_cmd", "nix --version", nil, nil)
	testing.expect(t, d == .Allow, "nix --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nix flake show", nil, nil)
	testing.expect(t, d == .Allow, "nix flake show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nix flake metadata", nil, nil)
	testing.expect(t, d == .Allow, "nix flake metadata auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nix search nixpkgs hello", nil, nil)
	testing.expect(t, d == .Allow, "nix search auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nix doctor", nil, nil)
	testing.expect(t, d == .Allow, "nix doctor auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nix build", nil, nil)
	testing.expect(t, d == .Ask, "nix build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nix run", nil, nil)
	testing.expect(t, d == .Ask, "nix run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nix-shell", nil, nil)
	testing.expect(t, d == .Ask, "bare nix-shell asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nix-env -q", nil, nil)
	testing.expect(t, d == .Allow, "nix-env -q auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nixos-version", nil, nil)
	testing.expect(t, d == .Allow, "nixos-version auto-allow")
	// B56: aws inspect
	d = check_tool(.Ask, "run_terminal_cmd", "aws sts get-caller-identity", nil, nil)
	testing.expect(t, d == .Allow, "aws sts get-caller-identity auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "aws s3 ls", nil, nil)
	testing.expect(t, d == .Allow, "aws s3 ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "aws ec2 describe-instances", nil, nil)
	testing.expect(t, d == .Allow, "aws ec2 describe auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "aws --region us-east-1 s3 ls", nil, nil)
	testing.expect(t, d == .Allow, "aws --region s3 ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "aws s3 cp s3://b/k .", nil, nil)
	testing.expect(t, d == .Ask, "aws s3 cp asks")
	d = check_tool(.Ask, "run_terminal_cmd", "aws s3 rm s3://b/k", nil, nil)
	testing.expect(t, d == .Ask, "aws s3 rm asks")
	d = check_tool(.Ask, "run_terminal_cmd", "aws ec2 terminate-instances --instance-ids i-x", nil, nil)
	testing.expect(t, d == .Ask, "aws terminate asks")
	// B57: gcloud / az inspect
	d = check_tool(.Ask, "run_terminal_cmd", "gcloud info", nil, nil)
	testing.expect(t, d == .Allow, "gcloud info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gcloud projects list", nil, nil)
	testing.expect(t, d == .Allow, "gcloud projects list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gcloud compute instances list", nil, nil)
	testing.expect(t, d == .Allow, "gcloud compute instances list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gcloud --project my-proj config list", nil, nil)
	testing.expect(t, d == .Allow, "gcloud --project config list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gcloud compute instances create n1 --zone=us", nil, nil)
	testing.expect(t, d == .Ask, "gcloud create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gcloud compute instances delete n1", nil, nil)
	testing.expect(t, d == .Ask, "gcloud delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "az version", nil, nil)
	testing.expect(t, d == .Allow, "az version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "az account show", nil, nil)
	testing.expect(t, d == .Allow, "az account show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "az vm list", nil, nil)
	testing.expect(t, d == .Allow, "az vm list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "az group list -o table", nil, nil)
	testing.expect(t, d == .Allow, "az group list -o table auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "az vm create -n n -g g", nil, nil)
	testing.expect(t, d == .Ask, "az vm create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "az group delete -n g", nil, nil)
	testing.expect(t, d == .Ask, "az group delete asks")
	// B58: podman + brew inspect
	d = check_tool(.Ask, "run_terminal_cmd", "podman ps", nil, nil)
	testing.expect(t, d == .Allow, "podman ps auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "podman images", nil, nil)
	testing.expect(t, d == .Allow, "podman images auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "podman compose ps", nil, nil)
	testing.expect(t, d == .Allow, "podman compose ps auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "podman run -it alpine", nil, nil)
	testing.expect(t, d == .Ask, "podman run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "brew list", nil, nil)
	testing.expect(t, d == .Allow, "brew list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "brew info odin", nil, nil)
	testing.expect(t, d == .Allow, "brew info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "brew search ripgrep", nil, nil)
	testing.expect(t, d == .Allow, "brew search auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "brew outdated", nil, nil)
	testing.expect(t, d == .Allow, "brew outdated auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "brew --version", nil, nil)
	testing.expect(t, d == .Allow, "brew --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "brew services list", nil, nil)
	testing.expect(t, d == .Allow, "brew services list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "brew install foo", nil, nil)
	testing.expect(t, d == .Ask, "brew install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "brew upgrade", nil, nil)
	testing.expect(t, d == .Ask, "brew upgrade asks")
	d = check_tool(.Ask, "run_terminal_cmd", "brew update", nil, nil)
	testing.expect(t, d == .Ask, "brew update asks")
	d = check_tool(.Ask, "run_terminal_cmd", "brew services start foo", nil, nil)
	testing.expect(t, d == .Ask, "brew services start asks")
	// B59: apt / dnf / pacman inspect
	d = check_tool(.Ask, "run_terminal_cmd", "apt list --installed", nil, nil)
	testing.expect(t, d == .Allow, "apt list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "apt search ripgrep", nil, nil)
	testing.expect(t, d == .Allow, "apt search auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "apt show curl", nil, nil)
	testing.expect(t, d == .Allow, "apt show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "apt-cache policy git", nil, nil)
	testing.expect(t, d == .Allow, "apt-cache policy auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "apt install foo", nil, nil)
	testing.expect(t, d == .Ask, "apt install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "apt-get update", nil, nil)
	testing.expect(t, d == .Ask, "apt-get update asks")
	d = check_tool(.Ask, "run_terminal_cmd", "dnf list installed", nil, nil)
	testing.expect(t, d == .Allow, "dnf list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dnf info bash", nil, nil)
	testing.expect(t, d == .Allow, "dnf info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dnf repolist", nil, nil)
	testing.expect(t, d == .Allow, "dnf repolist auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "yum search nginx", nil, nil)
	testing.expect(t, d == .Allow, "yum search auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dnf install foo", nil, nil)
	testing.expect(t, d == .Ask, "dnf install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pacman -Q", nil, nil)
	testing.expect(t, d == .Allow, "pacman -Q auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pacman -Ss ripgrep", nil, nil)
	testing.expect(t, d == .Allow, "pacman -Ss auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pacman -Si bash", nil, nil)
	testing.expect(t, d == .Allow, "pacman -Si auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pacman -S foo", nil, nil)
	testing.expect(t, d == .Ask, "pacman -S install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pacman -Syu", nil, nil)
	testing.expect(t, d == .Ask, "pacman -Syu asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pacman -R foo", nil, nil)
	testing.expect(t, d == .Ask, "pacman -R asks")
	// B60: flatpak / snap / apk inspect
	d = check_tool(.Ask, "run_terminal_cmd", "flatpak list", nil, nil)
	testing.expect(t, d == .Allow, "flatpak list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flatpak search firefox", nil, nil)
	testing.expect(t, d == .Allow, "flatpak search auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flatpak remote-list", nil, nil)
	testing.expect(t, d == .Allow, "flatpak remote-list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flatpak install flathub org.foo", nil, nil)
	testing.expect(t, d == .Ask, "flatpak install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "flatpak run org.foo", nil, nil)
	testing.expect(t, d == .Ask, "flatpak run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "snap list", nil, nil)
	testing.expect(t, d == .Allow, "snap list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "snap info code", nil, nil)
	testing.expect(t, d == .Allow, "snap info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "snap find code", nil, nil)
	testing.expect(t, d == .Allow, "snap find auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "snap install code", nil, nil)
	testing.expect(t, d == .Ask, "snap install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "snap refresh", nil, nil)
	testing.expect(t, d == .Ask, "snap refresh asks")
	d = check_tool(.Ask, "run_terminal_cmd", "apk info bash", nil, nil)
	testing.expect(t, d == .Allow, "apk info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "apk search curl", nil, nil)
	testing.expect(t, d == .Allow, "apk search auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "apk version", nil, nil)
	testing.expect(t, d == .Allow, "apk version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "apk add curl", nil, nil)
	testing.expect(t, d == .Ask, "apk add asks")
	d = check_tool(.Ask, "run_terminal_cmd", "apk upgrade", nil, nil)
	testing.expect(t, d == .Ask, "apk upgrade asks")
	// B64: pipx / gem / composer inspect
	d = check_tool(.Ask, "run_terminal_cmd", "pipx list", nil, nil)
	testing.expect(t, d == .Allow, "pipx list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pipx environment", nil, nil)
	testing.expect(t, d == .Allow, "pipx environment auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pipx install ruff", nil, nil)
	testing.expect(t, d == .Ask, "pipx install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pipx run cowsay hi", nil, nil)
	testing.expect(t, d == .Ask, "pipx run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gem list", nil, nil)
	testing.expect(t, d == .Allow, "gem list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gem search rails", nil, nil)
	testing.expect(t, d == .Allow, "gem search auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gem environment", nil, nil)
	testing.expect(t, d == .Allow, "gem environment auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gem outdated", nil, nil)
	testing.expect(t, d == .Allow, "gem outdated auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gem install bundler", nil, nil)
	testing.expect(t, d == .Ask, "gem install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gem sources --add https://x", nil, nil)
	testing.expect(t, d == .Ask, "gem sources --add asks")
	d = check_tool(.Ask, "run_terminal_cmd", "composer show", nil, nil)
	testing.expect(t, d == .Allow, "composer show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "composer outdated", nil, nil)
	testing.expect(t, d == .Allow, "composer outdated auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "composer validate", nil, nil)
	testing.expect(t, d == .Allow, "composer validate auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "composer install", nil, nil)
	testing.expect(t, d == .Ask, "composer install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "composer require foo/bar", nil, nil)
	testing.expect(t, d == .Ask, "composer require asks")
	// B66: bundle / rake inspect
	d = check_tool(.Ask, "run_terminal_cmd", "bundle list", nil, nil)
	testing.expect(t, d == .Allow, "bundle list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle show rails", nil, nil)
	testing.expect(t, d == .Allow, "bundle show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle check", nil, nil)
	testing.expect(t, d == .Allow, "bundle check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle outdated", nil, nil)
	testing.expect(t, d == .Allow, "bundle outdated auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle env", nil, nil)
	testing.expect(t, d == .Allow, "bundle env auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle config list", nil, nil)
	testing.expect(t, d == .Allow, "bundle config list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle install", nil, nil)
	testing.expect(t, d == .Ask, "bundle install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle exec rspec", nil, nil)
	testing.expect(t, d == .Ask, "bundle exec asks")
	d = check_tool(.Ask, "run_terminal_cmd", "bundle update", nil, nil)
	testing.expect(t, d == .Ask, "bundle update asks")
	d = check_tool(.Ask, "run_terminal_cmd", "rake -T", nil, nil)
	testing.expect(t, d == .Allow, "rake -T auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "rake --tasks", nil, nil)
	testing.expect(t, d == .Allow, "rake --tasks auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "rake -D", nil, nil)
	testing.expect(t, d == .Allow, "rake -D auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "rake", nil, nil)
	testing.expect(t, d == .Ask, "bare rake asks")
	d = check_tool(.Ask, "run_terminal_cmd", "rake db:migrate", nil, nil)
	testing.expect(t, d == .Ask, "rake task asks")
	// B67: mvn / gradle inspect
	d = check_tool(.Ask, "run_terminal_cmd", "mvn --version", nil, nil)
	testing.expect(t, d == .Allow, "mvn --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "mvn dependency:tree", nil, nil)
	testing.expect(t, d == .Allow, "mvn dependency:tree auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "mvn help:effective-pom", nil, nil)
	testing.expect(t, d == .Allow, "mvn help:effective-pom auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "mvn package", nil, nil)
	testing.expect(t, d == .Ask, "mvn package asks")
	d = check_tool(.Ask, "run_terminal_cmd", "mvn install", nil, nil)
	testing.expect(t, d == .Ask, "mvn install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "mvn test", nil, nil)
	testing.expect(t, d == .Ask, "mvn test asks")
	d = check_tool(.Ask, "run_terminal_cmd", "mvnw dependency:tree", nil, nil)
	testing.expect(t, d == .Allow, "mvnw dependency:tree auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gradle tasks", nil, nil)
	testing.expect(t, d == .Allow, "gradle tasks auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gradle dependencies", nil, nil)
	testing.expect(t, d == .Allow, "gradle dependencies auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gradle projects", nil, nil)
	testing.expect(t, d == .Allow, "gradle projects auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gradle --version", nil, nil)
	testing.expect(t, d == .Allow, "gradle --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "gradle build", nil, nil)
	testing.expect(t, d == .Ask, "gradle build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gradle test", nil, nil)
	testing.expect(t, d == .Ask, "gradle test asks")
	d = check_tool(.Ask, "run_terminal_cmd", "gradlew tasks", nil, nil)
	testing.expect(t, d == .Allow, "gradlew tasks auto-allow")
	// B69: sbt inspect
	d = check_tool(.Ask, "run_terminal_cmd", "sbt --version", nil, nil)
	testing.expect(t, d == .Allow, "sbt --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt tasks", nil, nil)
	testing.expect(t, d == .Allow, "sbt tasks auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt about", nil, nil)
	testing.expect(t, d == .Allow, "sbt about auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt dependencyTree", nil, nil)
	testing.expect(t, d == .Allow, "sbt dependencyTree auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt show", nil, nil)
	testing.expect(t, d == .Allow, "sbt show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt", nil, nil)
	testing.expect(t, d == .Ask, "bare sbt asks")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt compile", nil, nil)
	testing.expect(t, d == .Ask, "sbt compile asks")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt test", nil, nil)
	testing.expect(t, d == .Ask, "sbt test asks")
	d = check_tool(.Ask, "run_terminal_cmd", "sbt run", nil, nil)
	testing.expect(t, d == .Ask, "sbt run asks")
	// B70: bazel / bazelisk inspect
	d = check_tool(.Ask, "run_terminal_cmd", "bazel version", nil, nil)
	testing.expect(t, d == .Allow, "bazel version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel info", nil, nil)
	testing.expect(t, d == .Allow, "bazel info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel query //...", nil, nil)
	testing.expect(t, d == .Allow, "bazel query auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel cquery //foo:bar", nil, nil)
	testing.expect(t, d == .Allow, "bazel cquery auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel help build", nil, nil)
	testing.expect(t, d == .Allow, "bazel help auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bazelisk version", nil, nil)
	testing.expect(t, d == .Allow, "bazelisk version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel build //...", nil, nil)
	testing.expect(t, d == .Ask, "bazel build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel test //...", nil, nil)
	testing.expect(t, d == .Ask, "bazel test asks")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel run //foo:bin", nil, nil)
	testing.expect(t, d == .Ask, "bazel run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "bazel clean", nil, nil)
	testing.expect(t, d == .Ask, "bazel clean asks")
	// B71: pulumi inspect
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi version", nil, nil)
	testing.expect(t, d == .Allow, "pulumi version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi whoami", nil, nil)
	testing.expect(t, d == .Allow, "pulumi whoami auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi stack ls", nil, nil)
	testing.expect(t, d == .Allow, "pulumi stack ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi stack output", nil, nil)
	testing.expect(t, d == .Allow, "pulumi stack output auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi config", nil, nil)
	testing.expect(t, d == .Allow, "pulumi config auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi config get foo", nil, nil)
	testing.expect(t, d == .Allow, "pulumi config get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi about", nil, nil)
	testing.expect(t, d == .Allow, "pulumi about auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi up", nil, nil)
	testing.expect(t, d == .Ask, "pulumi up asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi destroy", nil, nil)
	testing.expect(t, d == .Ask, "pulumi destroy asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi preview", nil, nil)
	testing.expect(t, d == .Ask, "pulumi preview asks")
	d = check_tool(.Ask, "run_terminal_cmd", "pulumi config set foo bar", nil, nil)
	testing.expect(t, d == .Ask, "pulumi config set asks")
	// B72: ansible family inspect
	d = check_tool(.Ask, "run_terminal_cmd", "ansible --version", nil, nil)
	testing.expect(t, d == .Allow, "ansible --version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible all --list-hosts -i hosts", nil, nil)
	testing.expect(t, d == .Allow, "ansible --list-hosts auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible all -m ping -i hosts", nil, nil)
	testing.expect(t, d == .Ask, "ansible -m ping asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-playbook site.yml --list-tasks", nil, nil)
	testing.expect(t, d == .Allow, "ansible-playbook --list-tasks auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-playbook site.yml --syntax-check", nil, nil)
	testing.expect(t, d == .Allow, "ansible-playbook --syntax-check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-playbook site.yml", nil, nil)
	testing.expect(t, d == .Ask, "ansible-playbook apply asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-inventory -i hosts --list", nil, nil)
	testing.expect(t, d == .Allow, "ansible-inventory --list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-doc -l", nil, nil)
	testing.expect(t, d == .Allow, "ansible-doc -l auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-galaxy collection list", nil, nil)
	testing.expect(t, d == .Allow, "ansible-galaxy collection list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-galaxy collection install community.general", nil, nil)
	testing.expect(t, d == .Ask, "ansible-galaxy install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ansible-config dump", nil, nil)
	testing.expect(t, d == .Allow, "ansible-config dump auto-allow")
	// B73: vagrant inspect
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant status", nil, nil)
	testing.expect(t, d == .Allow, "vagrant status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant global-status", nil, nil)
	testing.expect(t, d == .Allow, "vagrant global-status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant box list", nil, nil)
	testing.expect(t, d == .Allow, "vagrant box list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant validate", nil, nil)
	testing.expect(t, d == .Allow, "vagrant validate auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant version", nil, nil)
	testing.expect(t, d == .Allow, "vagrant version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant ssh-config", nil, nil)
	testing.expect(t, d == .Allow, "vagrant ssh-config auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant up", nil, nil)
	testing.expect(t, d == .Ask, "vagrant up asks")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant destroy -f", nil, nil)
	testing.expect(t, d == .Ask, "vagrant destroy asks")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant ssh", nil, nil)
	testing.expect(t, d == .Ask, "vagrant ssh asks")
	d = check_tool(.Ask, "run_terminal_cmd", "vagrant box add ubuntu/jammy64", nil, nil)
	testing.expect(t, d == .Ask, "vagrant box add asks")
	// B74: packer inspect
	d = check_tool(.Ask, "run_terminal_cmd", "packer version", nil, nil)
	testing.expect(t, d == .Allow, "packer version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "packer validate template.pkr.hcl", nil, nil)
	testing.expect(t, d == .Allow, "packer validate auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "packer inspect template.pkr.hcl", nil, nil)
	testing.expect(t, d == .Allow, "packer inspect auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "packer fmt -check .", nil, nil)
	testing.expect(t, d == .Allow, "packer fmt -check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "packer fmt .", nil, nil)
	testing.expect(t, d == .Ask, "packer fmt write asks")
	d = check_tool(.Ask, "run_terminal_cmd", "packer build template.pkr.hcl", nil, nil)
	testing.expect(t, d == .Ask, "packer build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "packer init .", nil, nil)
	testing.expect(t, d == .Ask, "packer init asks")
	// B75: consul / nomad inspect
	d = check_tool(.Ask, "run_terminal_cmd", "consul version", nil, nil)
	testing.expect(t, d == .Allow, "consul version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "consul members", nil, nil)
	testing.expect(t, d == .Allow, "consul members auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "consul catalog services", nil, nil)
	testing.expect(t, d == .Allow, "consul catalog services auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "consul kv get foo", nil, nil)
	testing.expect(t, d == .Allow, "consul kv get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "consul info", nil, nil)
	testing.expect(t, d == .Allow, "consul info auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "consul kv put foo bar", nil, nil)
	testing.expect(t, d == .Ask, "consul kv put asks")
	d = check_tool(.Ask, "run_terminal_cmd", "consul join 10.0.0.2", nil, nil)
	testing.expect(t, d == .Ask, "consul join asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad version", nil, nil)
	testing.expect(t, d == .Allow, "nomad version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad status", nil, nil)
	testing.expect(t, d == .Allow, "nomad status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad node status", nil, nil)
	testing.expect(t, d == .Allow, "nomad node status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad job status", nil, nil)
	testing.expect(t, d == .Allow, "nomad job status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad job plan job.nomad", nil, nil)
	testing.expect(t, d == .Allow, "nomad job plan auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad alloc logs abc", nil, nil)
	testing.expect(t, d == .Allow, "nomad alloc logs auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad run job.nomad", nil, nil)
	testing.expect(t, d == .Ask, "nomad run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad stop job1", nil, nil)
	testing.expect(t, d == .Ask, "nomad stop asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nomad alloc exec abc sh", nil, nil)
	testing.expect(t, d == .Ask, "nomad alloc exec asks")
	// B76: vault inspect (no secret reads)
	d = check_tool(.Ask, "run_terminal_cmd", "vault status", nil, nil)
	testing.expect(t, d == .Allow, "vault status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vault version", nil, nil)
	testing.expect(t, d == .Allow, "vault version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vault secrets list", nil, nil)
	testing.expect(t, d == .Allow, "vault secrets list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vault auth list", nil, nil)
	testing.expect(t, d == .Allow, "vault auth list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vault policy list", nil, nil)
	testing.expect(t, d == .Allow, "vault policy list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vault operator raft list-peers", nil, nil)
	testing.expect(t, d == .Allow, "vault operator raft list-peers auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "vault kv get secret/foo", nil, nil)
	testing.expect(t, d == .Ask, "vault kv get asks")
	d = check_tool(.Ask, "run_terminal_cmd", "vault read secret/foo", nil, nil)
	testing.expect(t, d == .Ask, "vault read asks")
	d = check_tool(.Ask, "run_terminal_cmd", "vault write secret/foo bar=1", nil, nil)
	testing.expect(t, d == .Ask, "vault write asks")
	d = check_tool(.Ask, "run_terminal_cmd", "vault login", nil, nil)
	testing.expect(t, d == .Ask, "vault login asks")
	// B77: argocd inspect
	d = check_tool(.Ask, "run_terminal_cmd", "argocd version", nil, nil)
	testing.expect(t, d == .Allow, "argocd version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd app list", nil, nil)
	testing.expect(t, d == .Allow, "argocd app list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd app get myapp", nil, nil)
	testing.expect(t, d == .Allow, "argocd app get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd app diff myapp", nil, nil)
	testing.expect(t, d == .Allow, "argocd app diff auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd cluster list", nil, nil)
	testing.expect(t, d == .Allow, "argocd cluster list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd repo list", nil, nil)
	testing.expect(t, d == .Allow, "argocd repo list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd app sync myapp", nil, nil)
	testing.expect(t, d == .Ask, "argocd app sync asks")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd app delete myapp", nil, nil)
	testing.expect(t, d == .Ask, "argocd app delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "argocd login argocd.example.com", nil, nil)
	testing.expect(t, d == .Ask, "argocd login asks")
	// B78: flux inspect
	d = check_tool(.Ask, "run_terminal_cmd", "flux version", nil, nil)
	testing.expect(t, d == .Allow, "flux version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flux check", nil, nil)
	testing.expect(t, d == .Allow, "flux check auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flux get sources git", nil, nil)
	testing.expect(t, d == .Allow, "flux get sources git auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flux get kustomizations", nil, nil)
	testing.expect(t, d == .Allow, "flux get kustomizations auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flux logs", nil, nil)
	testing.expect(t, d == .Allow, "flux logs auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flux tree kustomization flux-system", nil, nil)
	testing.expect(t, d == .Allow, "flux tree auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flux export source git flux-system", nil, nil)
	testing.expect(t, d == .Allow, "flux export auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "flux reconcile kustomization flux-system", nil, nil)
	testing.expect(t, d == .Ask, "flux reconcile asks")
	d = check_tool(.Ask, "run_terminal_cmd", "flux create source git foo", nil, nil)
	testing.expect(t, d == .Ask, "flux create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "flux bootstrap github", nil, nil)
	testing.expect(t, d == .Ask, "flux bootstrap asks")
	d = check_tool(.Ask, "run_terminal_cmd", "flux suspend kustomization flux-system", nil, nil)
	testing.expect(t, d == .Ask, "flux suspend asks")
	// B79: istioctl inspect
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl version", nil, nil)
	testing.expect(t, d == .Allow, "istioctl version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl proxy-status", nil, nil)
	testing.expect(t, d == .Allow, "istioctl proxy-status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl analyze", nil, nil)
	testing.expect(t, d == .Allow, "istioctl analyze auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl proxy-config cluster deploy/foo", nil, nil)
	testing.expect(t, d == .Allow, "istioctl proxy-config auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl validate -f mesh.yaml", nil, nil)
	testing.expect(t, d == .Allow, "istioctl validate auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl install", nil, nil)
	testing.expect(t, d == .Ask, "istioctl install asks")
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl uninstall --purge", nil, nil)
	testing.expect(t, d == .Ask, "istioctl uninstall asks")
	d = check_tool(.Ask, "run_terminal_cmd", "istioctl apply -f x.yaml", nil, nil)
	testing.expect(t, d == .Ask, "istioctl apply asks")
	// B81: kustomize / kubectx / kubens
	d = check_tool(.Ask, "run_terminal_cmd", "kustomize version", nil, nil)
	testing.expect(t, d == .Allow, "kustomize version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kustomize build .", nil, nil)
	testing.expect(t, d == .Allow, "kustomize build auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kustomize build . -o out.yaml", nil, nil)
	testing.expect(t, d == .Ask, "kustomize build -o file asks")
	d = check_tool(.Ask, "run_terminal_cmd", "kustomize edit set image x=y", nil, nil)
	testing.expect(t, d == .Ask, "kustomize edit asks")
	d = check_tool(.Ask, "run_terminal_cmd", "kustomize create", nil, nil)
	testing.expect(t, d == .Ask, "kustomize create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "kubectx", nil, nil)
	testing.expect(t, d == .Allow, "kubectx list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubectx --current", nil, nil)
	testing.expect(t, d == .Allow, "kubectx --current auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubectx minikube", nil, nil)
	testing.expect(t, d == .Ask, "kubectx switch asks")
	d = check_tool(.Ask, "run_terminal_cmd", "kubens", nil, nil)
	testing.expect(t, d == .Allow, "kubens list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubens --current", nil, nil)
	testing.expect(t, d == .Allow, "kubens --current auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubens kube-system", nil, nil)
	testing.expect(t, d == .Ask, "kubens switch asks")
	// B82: skaffold inspect
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold version", nil, nil)
	testing.expect(t, d == .Allow, "skaffold version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold diagnose", nil, nil)
	testing.expect(t, d == .Allow, "skaffold diagnose auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold render", nil, nil)
	testing.expect(t, d == .Allow, "skaffold render auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold schema get", nil, nil)
	testing.expect(t, d == .Allow, "skaffold schema get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold config list", nil, nil)
	testing.expect(t, d == .Allow, "skaffold config list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold run", nil, nil)
	testing.expect(t, d == .Ask, "skaffold run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold dev", nil, nil)
	testing.expect(t, d == .Ask, "skaffold dev asks")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold delete", nil, nil)
	testing.expect(t, d == .Ask, "skaffold delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "skaffold build", nil, nil)
	testing.expect(t, d == .Ask, "skaffold build asks")
	// B83: kind / minikube inspect
	d = check_tool(.Ask, "run_terminal_cmd", "kind version", nil, nil)
	testing.expect(t, d == .Allow, "kind version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kind get clusters", nil, nil)
	testing.expect(t, d == .Allow, "kind get clusters auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kind get nodes", nil, nil)
	testing.expect(t, d == .Allow, "kind get nodes auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kind get kubeconfig", nil, nil)
	testing.expect(t, d == .Allow, "kind get kubeconfig auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kind create cluster", nil, nil)
	testing.expect(t, d == .Ask, "kind create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "kind delete cluster", nil, nil)
	testing.expect(t, d == .Ask, "kind delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "kind load docker-image foo", nil, nil)
	testing.expect(t, d == .Ask, "kind load asks")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube version", nil, nil)
	testing.expect(t, d == .Allow, "minikube version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube status", nil, nil)
	testing.expect(t, d == .Allow, "minikube status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube profile list", nil, nil)
	testing.expect(t, d == .Allow, "minikube profile list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube ip", nil, nil)
	testing.expect(t, d == .Allow, "minikube ip auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube addons list", nil, nil)
	testing.expect(t, d == .Allow, "minikube addons list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube start", nil, nil)
	testing.expect(t, d == .Ask, "minikube start asks")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube stop", nil, nil)
	testing.expect(t, d == .Ask, "minikube stop asks")
	d = check_tool(.Ask, "run_terminal_cmd", "minikube delete", nil, nil)
	testing.expect(t, d == .Ask, "minikube delete asks")
	// B84: k3d / tilt inspect
	d = check_tool(.Ask, "run_terminal_cmd", "k3d version", nil, nil)
	testing.expect(t, d == .Allow, "k3d version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "k3d cluster list", nil, nil)
	testing.expect(t, d == .Allow, "k3d cluster list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "k3d node list", nil, nil)
	testing.expect(t, d == .Allow, "k3d node list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "k3d kubeconfig get c1", nil, nil)
	testing.expect(t, d == .Allow, "k3d kubeconfig get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "k3d cluster create c1", nil, nil)
	testing.expect(t, d == .Ask, "k3d cluster create asks")
	d = check_tool(.Ask, "run_terminal_cmd", "k3d cluster delete c1", nil, nil)
	testing.expect(t, d == .Ask, "k3d cluster delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "tilt version", nil, nil)
	testing.expect(t, d == .Allow, "tilt version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tilt describe", nil, nil)
	testing.expect(t, d == .Allow, "tilt describe auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tilt get uiresources", nil, nil)
	testing.expect(t, d == .Allow, "tilt get auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tilt args", nil, nil)
	testing.expect(t, d == .Allow, "tilt args auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tilt up", nil, nil)
	testing.expect(t, d == .Ask, "tilt up asks")
	d = check_tool(.Ask, "run_terminal_cmd", "tilt down", nil, nil)
	testing.expect(t, d == .Ask, "tilt down asks")
	d = check_tool(.Ask, "run_terminal_cmd", "tilt ci", nil, nil)
	testing.expect(t, d == .Ask, "tilt ci asks")
	// B85: crane / skopeo / dive
	d = check_tool(.Ask, "run_terminal_cmd", "crane version", nil, nil)
	testing.expect(t, d == .Allow, "crane version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "crane digest ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "crane digest auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "crane manifest alpine:3", nil, nil)
	testing.expect(t, d == .Allow, "crane manifest auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "crane ls ghcr.io/foo/bar", nil, nil)
	testing.expect(t, d == .Allow, "crane ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "crane push ./dir img:tag", nil, nil)
	testing.expect(t, d == .Ask, "crane push asks")
	d = check_tool(.Ask, "run_terminal_cmd", "crane delete img:tag", nil, nil)
	testing.expect(t, d == .Ask, "crane delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "skopeo inspect docker://alpine:3", nil, nil)
	testing.expect(t, d == .Allow, "skopeo inspect auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "skopeo list-tags docker://alpine", nil, nil)
	testing.expect(t, d == .Allow, "skopeo list-tags auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "skopeo copy docker://a docker://b", nil, nil)
	testing.expect(t, d == .Ask, "skopeo copy asks")
	d = check_tool(.Ask, "run_terminal_cmd", "skopeo delete docker://a", nil, nil)
	testing.expect(t, d == .Ask, "skopeo delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "dive alpine:3", nil, nil)
	testing.expect(t, d == .Allow, "dive image auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dive version", nil, nil)
	testing.expect(t, d == .Allow, "dive version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "dive build -t x .", nil, nil)
	testing.expect(t, d == .Ask, "dive build asks")
	// B86: syft / grype / trivy
	d = check_tool(.Ask, "run_terminal_cmd", "syft version", nil, nil)
	testing.expect(t, d == .Allow, "syft version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "syft alpine:3", nil, nil)
	testing.expect(t, d == .Allow, "syft image scan auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "syft packages dir:.", nil, nil)
	testing.expect(t, d == .Allow, "syft packages auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "syft login -u u reg", nil, nil)
	testing.expect(t, d == .Ask, "syft login asks")
	d = check_tool(.Ask, "run_terminal_cmd", "syft alpine:3 --file out.json", nil, nil)
	testing.expect(t, d == .Ask, "syft --file asks")
	d = check_tool(.Ask, "run_terminal_cmd", "grype alpine:3", nil, nil)
	testing.expect(t, d == .Allow, "grype scan auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "grype version", nil, nil)
	testing.expect(t, d == .Allow, "grype version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "grype db status", nil, nil)
	testing.expect(t, d == .Allow, "grype db status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "grype db update", nil, nil)
	testing.expect(t, d == .Ask, "grype db update asks")
	d = check_tool(.Ask, "run_terminal_cmd", "grype db delete", nil, nil)
	testing.expect(t, d == .Ask, "grype db delete asks")
	d = check_tool(.Ask, "run_terminal_cmd", "trivy version", nil, nil)
	testing.expect(t, d == .Allow, "trivy version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "trivy image alpine:3", nil, nil)
	testing.expect(t, d == .Allow, "trivy image auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "trivy fs .", nil, nil)
	testing.expect(t, d == .Allow, "trivy fs auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "trivy config .", nil, nil)
	testing.expect(t, d == .Allow, "trivy config auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "trivy server", nil, nil)
	testing.expect(t, d == .Ask, "trivy server asks")
	d = check_tool(.Ask, "run_terminal_cmd", "trivy clean --all", nil, nil)
	testing.expect(t, d == .Ask, "trivy clean asks")
	d = check_tool(.Ask, "run_terminal_cmd", "trivy image alpine:3 -o report.json", nil, nil)
	testing.expect(t, d == .Ask, "trivy -o file asks")
	// B87: cosign / oras / regctl
	d = check_tool(.Ask, "run_terminal_cmd", "cosign version", nil, nil)
	testing.expect(t, d == .Allow, "cosign version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "cosign verify ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "cosign verify auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "cosign tree ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "cosign tree auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "cosign triangulate ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "cosign triangulate auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "cosign sign ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Ask, "cosign sign asks")
	d = check_tool(.Ask, "run_terminal_cmd", "cosign generate-key-pair", nil, nil)
	testing.expect(t, d == .Ask, "cosign generate-key-pair asks")
	d = check_tool(.Ask, "run_terminal_cmd", "oras version", nil, nil)
	testing.expect(t, d == .Allow, "oras version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "oras manifest fetch ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "oras manifest fetch auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "oras discover ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "oras discover auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "oras repo tags ghcr.io/foo/bar", nil, nil)
	testing.expect(t, d == .Allow, "oras repo tags auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "oras push ghcr.io/foo/bar:latest ./file", nil, nil)
	testing.expect(t, d == .Ask, "oras push asks")
	d = check_tool(.Ask, "run_terminal_cmd", "oras pull ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Ask, "oras pull asks")
	d = check_tool(.Ask, "run_terminal_cmd", "regctl version", nil, nil)
	testing.expect(t, d == .Allow, "regctl version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "regctl image digest ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "regctl image digest auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "regctl image manifest ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Allow, "regctl image manifest auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "regctl tag ls ghcr.io/foo/bar", nil, nil)
	testing.expect(t, d == .Allow, "regctl tag ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "regctl image copy a:1 b:2", nil, nil)
	testing.expect(t, d == .Ask, "regctl image copy asks")
	d = check_tool(.Ask, "run_terminal_cmd", "regctl image delete ghcr.io/foo/bar:latest", nil, nil)
	testing.expect(t, d == .Ask, "regctl image delete asks")
	// B88: buildah / nerdctl / ctr
	d = check_tool(.Ask, "run_terminal_cmd", "buildah version", nil, nil)
	testing.expect(t, d == .Allow, "buildah version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "buildah images", nil, nil)
	testing.expect(t, d == .Allow, "buildah images auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "buildah containers", nil, nil)
	testing.expect(t, d == .Allow, "buildah containers auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "buildah inspect alpine", nil, nil)
	testing.expect(t, d == .Allow, "buildah inspect auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "buildah bud -t x .", nil, nil)
	testing.expect(t, d == .Ask, "buildah bud asks")
	d = check_tool(.Ask, "run_terminal_cmd", "buildah from alpine", nil, nil)
	testing.expect(t, d == .Ask, "buildah from asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nerdctl version", nil, nil)
	testing.expect(t, d == .Allow, "nerdctl version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nerdctl ps", nil, nil)
	testing.expect(t, d == .Allow, "nerdctl ps auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nerdctl images", nil, nil)
	testing.expect(t, d == .Allow, "nerdctl images auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nerdctl logs c1", nil, nil)
	testing.expect(t, d == .Allow, "nerdctl logs auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "nerdctl run -d alpine", nil, nil)
	testing.expect(t, d == .Ask, "nerdctl run asks")
	d = check_tool(.Ask, "run_terminal_cmd", "nerdctl build -t x .", nil, nil)
	testing.expect(t, d == .Ask, "nerdctl build asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ctr version", nil, nil)
	testing.expect(t, d == .Allow, "ctr version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ctr images ls", nil, nil)
	testing.expect(t, d == .Allow, "ctr images ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ctr containers ls", nil, nil)
	testing.expect(t, d == .Allow, "ctr containers ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ctr tasks ls", nil, nil)
	testing.expect(t, d == .Allow, "ctr tasks ls auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "ctr images pull alpine:3", nil, nil)
	testing.expect(t, d == .Ask, "ctr images pull asks")
	d = check_tool(.Ask, "run_terminal_cmd", "ctr run alpine:3 c1", nil, nil)
	testing.expect(t, d == .Ask, "ctr run asks")
	// B89: helmfile / stern / kubeconform
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile version", nil, nil)
	testing.expect(t, d == .Allow, "helmfile version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile list", nil, nil)
	testing.expect(t, d == .Allow, "helmfile list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile status", nil, nil)
	testing.expect(t, d == .Allow, "helmfile status auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile template", nil, nil)
	testing.expect(t, d == .Allow, "helmfile template auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile lint", nil, nil)
	testing.expect(t, d == .Allow, "helmfile lint auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile diff", nil, nil)
	testing.expect(t, d == .Allow, "helmfile diff auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile apply", nil, nil)
	testing.expect(t, d == .Ask, "helmfile apply asks")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile sync", nil, nil)
	testing.expect(t, d == .Ask, "helmfile sync asks")
	d = check_tool(.Ask, "run_terminal_cmd", "helmfile destroy", nil, nil)
	testing.expect(t, d == .Ask, "helmfile destroy asks")
	d = check_tool(.Ask, "run_terminal_cmd", "stern app", nil, nil)
	testing.expect(t, d == .Allow, "stern query auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "stern --version", nil, nil)
	testing.expect(t, d == .Allow, "stern version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "stern --namespace kube-system -l app=x", nil, nil)
	testing.expect(t, d == .Allow, "stern flags auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubeconform --version", nil, nil)
	testing.expect(t, d == .Allow, "kubeconform version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubeconform deploy.yaml", nil, nil)
	testing.expect(t, d == .Allow, "kubeconform file auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubeconform -summary manifests/", nil, nil)
	testing.expect(t, d == .Allow, "kubeconform dir auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "kubeconform -cache /tmp/kc deploy.yaml", nil, nil)
	testing.expect(t, d == .Ask, "kubeconform -cache asks")
	// B90: tflint / terraform-docs / terragrunt
	d = check_tool(.Ask, "run_terminal_cmd", "tflint", nil, nil)
	testing.expect(t, d == .Allow, "tflint bare auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tflint --version", nil, nil)
	testing.expect(t, d == .Allow, "tflint version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tflint --chdir modules/net", nil, nil)
	testing.expect(t, d == .Allow, "tflint --chdir auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tflint --init", nil, nil)
	testing.expect(t, d == .Ask, "tflint --init asks")
	d = check_tool(.Ask, "run_terminal_cmd", "tflint --fix-config", nil, nil)
	testing.expect(t, d == .Ask, "tflint --fix-config asks")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform-docs --version", nil, nil)
	testing.expect(t, d == .Allow, "terraform-docs version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform-docs markdown .", nil, nil)
	testing.expect(t, d == .Allow, "terraform-docs markdown auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform-docs json ./module", nil, nil)
	testing.expect(t, d == .Allow, "terraform-docs json auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terraform-docs markdown . --output-file README.md", nil, nil)
	testing.expect(t, d == .Ask, "terraform-docs --output-file asks")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt plan", nil, nil)
	testing.expect(t, d == .Allow, "terragrunt plan auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt validate", nil, nil)
	testing.expect(t, d == .Allow, "terragrunt validate auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt show", nil, nil)
	testing.expect(t, d == .Allow, "terragrunt show auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt state list", nil, nil)
	testing.expect(t, d == .Allow, "terragrunt state list auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt run-all plan", nil, nil)
	testing.expect(t, d == .Allow, "terragrunt run-all plan auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt apply", nil, nil)
	testing.expect(t, d == .Ask, "terragrunt apply asks")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt destroy", nil, nil)
	testing.expect(t, d == .Ask, "terragrunt destroy asks")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt run-all apply", nil, nil)
	testing.expect(t, d == .Ask, "terragrunt run-all apply asks")
	d = check_tool(.Ask, "run_terminal_cmd", "terragrunt hclfmt", nil, nil)
	testing.expect(t, d == .Ask, "terragrunt hclfmt asks")
	// B91: checkov / tfsec / infracost
	d = check_tool(.Ask, "run_terminal_cmd", "checkov --version", nil, nil)
	testing.expect(t, d == .Allow, "checkov version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "checkov -d .", nil, nil)
	testing.expect(t, d == .Allow, "checkov -d auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "checkov -f main.tf", nil, nil)
	testing.expect(t, d == .Allow, "checkov -f auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "checkov --create-config", nil, nil)
	testing.expect(t, d == .Ask, "checkov --create-config asks")
	d = check_tool(.Ask, "run_terminal_cmd", "checkov -d . --output-file-path out", nil, nil)
	testing.expect(t, d == .Ask, "checkov --output-file-path asks")
	d = check_tool(.Ask, "run_terminal_cmd", "tfsec .", nil, nil)
	testing.expect(t, d == .Allow, "tfsec scan auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tfsec --version", nil, nil)
	testing.expect(t, d == .Allow, "tfsec version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "tfsec . --out report.json", nil, nil)
	testing.expect(t, d == .Ask, "tfsec --out asks")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost --version", nil, nil)
	testing.expect(t, d == .Allow, "infracost version auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost breakdown --path .", nil, nil)
	testing.expect(t, d == .Allow, "infracost breakdown auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost diff --path .", nil, nil)
	testing.expect(t, d == .Allow, "infracost diff auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost output --path out.json --format table", nil, nil)
	testing.expect(t, d == .Allow, "infracost output auto-allow")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost configure set api_key x", nil, nil)
	testing.expect(t, d == .Ask, "infracost configure asks")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost auth login", nil, nil)
	testing.expect(t, d == .Ask, "infracost auth asks")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost comment github --path x", nil, nil)
	testing.expect(t, d == .Ask, "infracost comment asks")
	d = check_tool(.Ask, "run_terminal_cmd", "infracost breakdown --path . --out-file cost.json", nil, nil)
	testing.expect(t, d == .Ask, "infracost --out-file asks")
	d = check_tool(.Read_Only, "run_terminal_cmd", "pwd", nil, nil)
	testing.expect(t, d == .Allow, "pwd in read-only mode")
	d = check_tool(.Read_Only, "run_terminal_cmd", "rm foo", nil, nil)
	testing.expect(t, d == .Deny, "rm denied in read-only")
	// chain: any write segment → not readonly
	d = check_tool(.Ask, "run_terminal_cmd", "ls && rm -rf /tmp/x", nil, nil)
	testing.expect(t, d == .Ask, "mixed chain still asks")
	// opt-out soft
	os.set_env("AETHER_NO_BASH_SOFT", "1")
	defer os.unset_env("AETHER_NO_BASH_SOFT")
	d = check_tool(.Always_Approve, "run_terminal_cmd", "rm -rf /", nil, nil)
	testing.expect(t, d == .Allow, "soft off allows under yolo")
}

@(test)
test_auto_mode_accepts_edits_asks_bash :: proc(t: ^testing.T) {
	d := check_tool(.Auto, "search_replace", "", nil, nil)
	testing.expect(t, d == .Allow, "edit allowed")
	d = check_tool(.Auto, "write", "", nil, nil)
	testing.expect(t, d == .Allow, "write allowed")
	d = check_tool(.Auto, "delete_file", "", nil, nil)
	testing.expect(t, d == .Allow, "delete allowed")
	d = check_tool(.Auto, "run_terminal_cmd", "rm staging", nil, nil)
	testing.expect(t, d == .Ask, "write bash asks")
	d = check_tool(.Auto, "use_tool", "", nil, nil)
	testing.expect(t, d == .Ask, "mcp asks")
	d = check_tool(.Auto, "read_file", "", nil, nil)
	testing.expect(t, d == .Allow, "read allowed")
	// deny still wins
	deny := []string{"Edit"}
	d = check_tool(.Auto, "write", "", nil, deny)
	testing.expect(t, d == .Deny, "deny Edit")
}

@(test)
test_permission_mode_string_round_trip :: proc(t: ^testing.T) {
	modes := []Permission_Mode{.Always_Approve, .Auto, .Read_Only, .Ask}
	for mode in modes {
		s := permission_mode_string(mode)
		got, ok := permission_mode_from_string(s)
		testing.expectf(t, ok, "parse %s", s)
		testing.expect(t, got == mode, "round-trip")
	}
	// aliases
	got, ok := permission_mode_from_string("yolo")
	testing.expect(t, ok && got == .Always_Approve, "yolo alias")
	got, ok = permission_mode_from_string("readonly")
	testing.expect(t, ok && got == .Read_Only, "readonly alias")
	got, ok = permission_mode_from_string("accept-edits")
	testing.expect(t, ok && got == .Auto, "accept-edits alias")
	got, ok = permission_mode_from_string("auto")
	testing.expect(t, ok && got == .Auto, "auto is Auto not yolo")
}

@(test)
test_rule_for_always_allow_bash_and_edit :: proc(t: ^testing.T) {
	r := rule_for_always_allow("search_replace", "", context.allocator)
	defer delete(r)
	testing.expect(t, r == "Edit")

	r2 := rule_for_always_allow("run_terminal_cmd", "ls -la /tmp", context.allocator)
	defer delete(r2)
	testing.expect(t, r2 == "Bash(ls *)")

	r3 := rule_for_always_allow("run_terminal_cmd", "git status --short", context.allocator)
	defer delete(r3)
	testing.expect(t, r3 == "Bash(git status *)")

	r4 := rule_for_always_allow("run_terminal_cmd", "cargo test --lib", context.allocator)
	defer delete(r4)
	// cargo test is safe two-word → scope 2
	testing.expect(t, r4 == "Bash(cargo test *)")

	r5 := rule_for_always_allow("use_tool", "", context.allocator)
	defer delete(r5)
	testing.expect(t, r5 == "")
}

@(test)
test_default_always_allow_scope :: proc(t: ^testing.T) {
	words := []string{"ls", "src/foo"}
	testing.expect(t, default_always_allow_scope(words) == 1)
	words2 := []string{"git", "status", "--short"}
	testing.expect(t, default_always_allow_scope(words2) == 2)
	words3 := []string{"kubectl", "get", "pods", "-o", "json"}
	testing.expect(t, default_always_allow_scope(words3) == 2)
	words4 := []string{"make", "build"}
	// not safe-listed → min(2, n) = 2
	testing.expect(t, default_always_allow_scope(words4) == 2)
}

@(test)
test_session_allow_grants_ask_mode :: proc(t: ^testing.T) {
	session_allow_clear()
	defer session_allow_clear()

	// Without grant → Ask (write-like shell; not soft-readonly)
	d := check_tool(.Ask, "run_terminal_cmd", "rm staging.txt", nil, nil)
	testing.expect(t, d == .Ask)

	session_allow_add("Bash(rm *)")
	allow := merge_allow_lists(nil, context.temp_allocator)
	d = check_tool(.Ask, "run_terminal_cmd", "rm staging.txt", allow, nil)
	testing.expect(t, d == .Allow, "session grant matches")
	d = check_tool(.Ask, "run_terminal_cmd", "touch other", allow, nil)
	testing.expect(t, d == .Ask, "other commands still ask")
}

@(test)
test_allow_rule_match_returns_allow :: proc(t: ^testing.T) {
	allow := []string{"Edit"}
	d := check_tool(.Ask, "search_replace", "", allow, nil)
	testing.expect(t, d == .Allow)
	testing.expect(t, match_rule("Bash(git status *)", "run_terminal_cmd", "git status -sb"))
	testing.expect(t, !match_rule("Bash(git status *)", "run_terminal_cmd", "git push"))
}

@(test)
test_session_deny_blocks_even_always_approve :: proc(t: ^testing.T) {
	session_deny_clear()
	defer session_deny_clear()

	d := check_tool(.Always_Approve, "run_terminal_cmd", "rm -rf /tmp/x", nil, nil)
	testing.expect(t, d == .Allow)

	session_deny_add("Bash(rm *)")
	deny := merge_deny_lists(nil, context.temp_allocator)
	d = check_tool(.Always_Approve, "run_terminal_cmd", "rm -rf /tmp/x", nil, deny)
	testing.expect(t, d == .Deny, "session deny wins over always-approve")
	d = check_tool(.Always_Approve, "run_terminal_cmd", "ls", nil, deny)
	testing.expect(t, d == .Allow, "other commands still allowed")
}
